### ISSUE TITLE
Add popular content

### ISSUE THREAD

**Issue by casperdcl** [astrochun/github-stats-pages#52]
Already supported from the *Traffic* page:

- Git clones (showing off)
- Visitors (showing off)
- Referring sites (analytics)

Missing:

- Popular content (prioritising product improvement)

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10780059/116797530-9689b180-aade-11eb-8ce2-c1a32f79e641.png)

</details>

**Comment by astrochun** [comment]
Thanks for the suggestions. I started with traffic data as that has a two-week expiration while other content can be aggregated easily and there are a number of tools in this domain.

As far as popular content, what I had in mind are:
1. Number of issues over time
2. Cumulative growth of stars/forks/etc.
3. Contribution history (distinguishing between commit, issues, PRs) (For commit, I believe GitHub only shows up to 1 year by default)

I'm sure I'm missing other stuff.

**Comment by casperdcl** [comment]
I'm talking about the "Popular content" section on the *Traffic* page. It's in exactly the same format as the "Referring sites" section to the left of it.

**Comment by astrochun** [comment]
> I'm talking about the "Popular content" section on the _Traffic_ page. It's in exactly the same format as the "Referring sites" section to the left of it.

Ah, yes.
